version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: coursemate-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CourseMate RAG API
  coursemate-api:
    build: .
    container_name: coursemate-api
    ports:
      - "8000:8000"
    volumes:
      - ./course_materials:/app/course_materials
      - ./extracted_images:/app/extracted_images
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - QDRANT_URL=http://qdrant:6333
      - API_HOST=0.0.0.0
      - API_PORT=8000
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama (for LLM models)
  ollama:
    image: ollama/ollama:latest
    container_name: coursemate-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_storage:
    driver: local
  ollama_data:
    driver: local 